-- TorqMind - Full Reset (DROP + CREATE) - v2
-- PT-BR/EN: Execute este arquivo no PGAdmin (Query Tool) conectado ao banco torqmind.
-- This script DROPS and RECREATES all TorqMind schemas (auth/app/stg/dw/mart/etl).
--
-- ✅ Multi-tenant: id_empresa (tenant) + id_filial (branch)
-- ✅ STG: raw JSONB + ingested_at
-- ✅ DW: dims + facts
-- ✅ MART: materialized views (fast dashboards)
-- ✅ ETL: watermark + run_all()

BEGIN;

-- 0) Extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1) Drop schemas (order matters)
DROP SCHEMA IF EXISTS mart CASCADE;
DROP SCHEMA IF EXISTS dw CASCADE;
DROP SCHEMA IF EXISTS stg CASCADE;
DROP SCHEMA IF EXISTS etl CASCADE;
DROP SCHEMA IF EXISTS app CASCADE;
DROP SCHEMA IF EXISTS auth CASCADE;

-- 2) Schemas
CREATE SCHEMA auth;
CREATE SCHEMA app;
CREATE SCHEMA stg;
CREATE SCHEMA dw;
CREATE SCHEMA mart;
CREATE SCHEMA etl;

-- =========================
-- APP helpers (for RLS / session context)
-- =========================
-- PT-BR: estas funções permitem que a API injete o escopo (role/tenant/branch) na sessão via SET LOCAL.
-- EN: these helpers allow the API to push role/tenant/branch to the DB session (SET LOCAL) to support RLS later.

CREATE OR REPLACE FUNCTION app.current_role()
RETURNS text AS $$
  SELECT current_setting('app.role', true);
$$ LANGUAGE sql STABLE;

CREATE OR REPLACE FUNCTION app.current_tenant()
RETURNS integer AS $$
  SELECT NULLIF(current_setting('app.tenant_id', true), '')::integer;
$$ LANGUAGE sql STABLE;

CREATE OR REPLACE FUNCTION app.current_branch()
RETURNS integer AS $$
  SELECT NULLIF(current_setting('app.branch_id', true), '')::integer;
$$ LANGUAGE sql STABLE;

-- =========================
-- AUTH (users + scopes)
-- =========================

CREATE TABLE auth.users (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email             text UNIQUE NOT NULL,
  password_hash     text NOT NULL,
  is_active         boolean NOT NULL DEFAULT true,
  created_at        timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE auth.user_tenants (
  user_id           uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role              text NOT NULL CHECK (role IN ('MASTER','OWNER','MANAGER')),
  id_empresa        integer NULL,
  id_filial         integer NULL,
  PRIMARY KEY (user_id, role, id_empresa, id_filial)
);

CREATE TABLE auth.audit_log (
  id                bigserial PRIMARY KEY,
  ts                timestamptz NOT NULL DEFAULT now(),
  actor_user_id     uuid NULL,
  action            text NOT NULL,
  meta              jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- Branch catalog for access/UI convenience (kept small)
CREATE TABLE auth.filiais (
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  nome              text NOT NULL DEFAULT '',
  is_active         boolean NOT NULL DEFAULT true,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, id_filial)
);

CREATE OR REPLACE FUNCTION auth.set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_auth_filiais_updated_at ON auth.filiais;
CREATE TRIGGER trg_auth_filiais_updated_at
BEFORE UPDATE ON auth.filiais
FOR EACH ROW EXECUTE FUNCTION auth.set_updated_at();

-- =========================
-- APP (tenants + notifications + goals)
-- =========================

CREATE TABLE app.tenants (
  id_empresa        integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nome              text NOT NULL,
  ingest_key        uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  source_system     text NOT NULL DEFAULT 'XPERT',
  is_active         boolean NOT NULL DEFAULT true,
  created_at        timestamptz NOT NULL DEFAULT now(),
  metadata          jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE app.user_notification_settings (
  user_id           uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  telegram_chat_id  text NULL,
  telegram_enabled  boolean NOT NULL DEFAULT false,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS trg_app_user_notification_updated_at ON app.user_notification_settings;
CREATE TRIGGER trg_app_user_notification_updated_at
BEFORE UPDATE ON app.user_notification_settings
FOR EACH ROW EXECUTE FUNCTION auth.set_updated_at();

-- Real-time alert table (idempotent per comprovante)
CREATE TABLE app.alert_comprovante_cancelado (
  id                bigserial PRIMARY KEY,
  created_at        timestamptz NOT NULL DEFAULT now(),
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  id_db             integer NOT NULL,
  id_comprovante    integer NOT NULL,
  comprovante_data  timestamp NULL,
  valor_total       numeric(18,2) NULL,
  id_usuario        integer NULL,
  id_turno          integer NULL,
  payload           jsonb NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (id_empresa, id_filial, id_db, id_comprovante)
);

-- Goals (for gamification / team)
CREATE TABLE app.goals (
  id                bigserial PRIMARY KEY,
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  goal_date         date NOT NULL,
  goal_type         text NOT NULL CHECK (goal_type IN (
                        'FATURAMENTO','MARGEM','TICKET','CANCELAMENTOS_MAX','INADIMPLENCIA_MAX'
                      )),
  target_value      numeric(18,2) NOT NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  UNIQUE (id_empresa, id_filial, goal_date, goal_type)
);

-- =========================
-- STG (raw JSONB)
-- =========================

-- NOTE: We keep only last version per PK (UPSERT). If you want full history, we can add a surrogate key later.

CREATE TABLE stg.filiais (
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  payload           jsonb NOT NULL,
  ingested_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, id_filial)
);
CREATE INDEX ix_stg_filiais_ing ON stg.filiais (id_empresa, ingested_at);

CREATE TABLE stg.funcionarios (
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  id_funcionario    integer NOT NULL,
  payload           jsonb NOT NULL,
  ingested_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, id_filial, id_funcionario)
);
CREATE INDEX ix_stg_funcionarios_ing ON stg.funcionarios (id_empresa, ingested_at);

CREATE TABLE stg.entidades (
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  id_entidade       integer NOT NULL,
  payload           jsonb NOT NULL,
  ingested_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, id_filial, id_entidade)
);
CREATE INDEX ix_stg_entidades_ing ON stg.entidades (id_empresa, ingested_at);

CREATE TABLE stg.grupoprodutos (
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  id_grupoprodutos  integer NOT NULL,
  payload           jsonb NOT NULL,
  ingested_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, id_filial, id_grupoprodutos)
);
CREATE INDEX ix_stg_grupoprodutos_ing ON stg.grupoprodutos (id_empresa, ingested_at);

CREATE TABLE stg.localvendas (
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  id_localvendas    integer NOT NULL,
  payload           jsonb NOT NULL,
  ingested_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, id_filial, id_localvendas)
);
CREATE INDEX ix_stg_localvendas_ing ON stg.localvendas (id_empresa, ingested_at);

CREATE TABLE stg.produtos (
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  id_produto        integer NOT NULL,
  payload           jsonb NOT NULL,
  ingested_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, id_filial, id_produto)
);
CREATE INDEX ix_stg_produtos_ing ON stg.produtos (id_empresa, ingested_at);

CREATE TABLE stg.turnos (
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  id_turno          integer NOT NULL,
  payload           jsonb NOT NULL,
  ingested_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, id_filial, id_turno)
);
CREATE INDEX ix_stg_turnos_ing ON stg.turnos (id_empresa, ingested_at);

CREATE TABLE stg.comprovantes (
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  id_db             integer NOT NULL,
  id_comprovante    integer NOT NULL,
  payload           jsonb NOT NULL,
  ingested_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, id_filial, id_db, id_comprovante)
);
CREATE INDEX ix_stg_comprovantes_ing ON stg.comprovantes (id_empresa, ingested_at);

CREATE TABLE stg.movprodutos (
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  id_db             integer NOT NULL,
  id_movprodutos    integer NOT NULL,
  payload           jsonb NOT NULL,
  ingested_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, id_filial, id_db, id_movprodutos)
);
CREATE INDEX ix_stg_movprodutos_ing ON stg.movprodutos (id_empresa, ingested_at);

CREATE TABLE stg.itensmovprodutos (
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  id_db             integer NOT NULL,
  id_movprodutos    integer NOT NULL,
  id_itensmovprodutos integer NOT NULL,
  payload           jsonb NOT NULL,
  ingested_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, id_filial, id_db, id_movprodutos, id_itensmovprodutos)
);
CREATE INDEX ix_stg_itensmovprodutos_ing ON stg.itensmovprodutos (id_empresa, ingested_at);

-- Finance raw tables (optional)
CREATE TABLE stg.contaspagar (
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  id_db             integer NOT NULL,
  id_contaspagar    integer NOT NULL,
  payload           jsonb NOT NULL,
  ingested_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, id_filial, id_db, id_contaspagar)
);
CREATE INDEX ix_stg_contaspagar_ing ON stg.contaspagar (id_empresa, ingested_at);

CREATE TABLE stg.contasreceber (
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  id_db             integer NOT NULL,
  id_contasreceber  integer NOT NULL,
  payload           jsonb NOT NULL,
  ingested_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, id_filial, id_db, id_contasreceber)
);
CREATE INDEX ix_stg_contasreceber_ing ON stg.contasreceber (id_empresa, ingested_at);

-- Unified financeiro dataset (optional alternative)
CREATE TABLE stg.financeiro (
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  id_db             integer NOT NULL,
  tipo_titulo       integer NOT NULL, -- 0 pagar, 1 receber
  id_titulo         integer NOT NULL,
  payload           jsonb NOT NULL,
  ingested_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, id_filial, id_db, tipo_titulo, id_titulo)
);
CREATE INDEX ix_stg_financeiro_ing ON stg.financeiro (id_empresa, ingested_at);

-- =========================
-- DW (dims + facts)
-- =========================

CREATE TABLE dw.dim_filial (
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  nome              text NOT NULL DEFAULT '',
  cnpj              text NULL,
  razao_social      text NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, id_filial)
);

DROP TRIGGER IF EXISTS trg_dw_dim_filial_updated_at ON dw.dim_filial;
CREATE TRIGGER trg_dw_dim_filial_updated_at
BEFORE UPDATE ON dw.dim_filial
FOR EACH ROW EXECUTE FUNCTION auth.set_updated_at();

CREATE TABLE dw.dim_grupo_produto (
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  id_grupo_produto  integer NOT NULL,
  nome              text NOT NULL DEFAULT '',
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, id_filial, id_grupo_produto)
);
DROP TRIGGER IF EXISTS trg_dw_dim_grupo_updated_at ON dw.dim_grupo_produto;
CREATE TRIGGER trg_dw_dim_grupo_updated_at
BEFORE UPDATE ON dw.dim_grupo_produto
FOR EACH ROW EXECUTE FUNCTION auth.set_updated_at();

CREATE TABLE dw.dim_local_venda (
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  id_local_venda    integer NOT NULL,
  nome              text NOT NULL DEFAULT '',
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, id_filial, id_local_venda)
);
DROP TRIGGER IF EXISTS trg_dw_dim_local_updated_at ON dw.dim_local_venda;
CREATE TRIGGER trg_dw_dim_local_updated_at
BEFORE UPDATE ON dw.dim_local_venda
FOR EACH ROW EXECUTE FUNCTION auth.set_updated_at();

CREATE TABLE dw.dim_produto (
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  id_produto        integer NOT NULL,
  nome              text NOT NULL DEFAULT '',
  unidade           text NULL,
  id_grupo_produto  integer NULL,
  id_local_venda    integer NULL,
  custo_medio       numeric(18,6) NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, id_filial, id_produto)
);
CREATE INDEX ix_dim_produto_grupo ON dw.dim_produto (id_empresa, id_filial, id_grupo_produto);
DROP TRIGGER IF EXISTS trg_dw_dim_produto_updated_at ON dw.dim_produto;
CREATE TRIGGER trg_dw_dim_produto_updated_at
BEFORE UPDATE ON dw.dim_produto
FOR EACH ROW EXECUTE FUNCTION auth.set_updated_at();

CREATE TABLE dw.dim_funcionario (
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  id_funcionario    integer NOT NULL,
  nome              text NOT NULL DEFAULT '',
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, id_filial, id_funcionario)
);
DROP TRIGGER IF EXISTS trg_dw_dim_func_updated_at ON dw.dim_funcionario;
CREATE TRIGGER trg_dw_dim_func_updated_at
BEFORE UPDATE ON dw.dim_funcionario
FOR EACH ROW EXECUTE FUNCTION auth.set_updated_at();

CREATE TABLE dw.dim_cliente (
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  id_cliente        integer NOT NULL,
  nome              text NOT NULL DEFAULT '',
  documento         text NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, id_filial, id_cliente)
);
DROP TRIGGER IF EXISTS trg_dw_dim_cliente_updated_at ON dw.dim_cliente;
CREATE TRIGGER trg_dw_dim_cliente_updated_at
BEFORE UPDATE ON dw.dim_cliente
FOR EACH ROW EXECUTE FUNCTION auth.set_updated_at();

CREATE TABLE dw.fact_comprovante (
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  id_db             integer NOT NULL,
  id_comprovante    integer NOT NULL,
  data              timestamp NULL,
  data_key          integer NULL,
  id_usuario        integer NULL,
  id_turno          integer NULL,
  id_cliente        integer NULL,
  valor_total       numeric(18,2) NULL,
  cancelado         boolean NOT NULL DEFAULT false,
  situacao          integer NULL,
  payload           jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, id_filial, id_db, id_comprovante)
);
CREATE INDEX ix_fact_comprovante_dt ON dw.fact_comprovante (id_empresa, data_key);
DROP TRIGGER IF EXISTS trg_dw_fact_comprovante_updated_at ON dw.fact_comprovante;
CREATE TRIGGER trg_dw_fact_comprovante_updated_at
BEFORE UPDATE ON dw.fact_comprovante
FOR EACH ROW EXECUTE FUNCTION auth.set_updated_at();

CREATE TABLE dw.fact_venda (
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  id_db             integer NOT NULL,
  id_movprodutos    integer NOT NULL,
  data              timestamp NULL,
  data_key          integer NULL,
  id_usuario        integer NULL,
  id_cliente        integer NULL,
  id_comprovante    integer NULL,
  id_turno          integer NULL,
  saidas_entradas   integer NULL,
  total_venda       numeric(18,2) NULL,
  cancelado         boolean NOT NULL DEFAULT false,
  payload           jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, id_filial, id_db, id_movprodutos)
);
CREATE INDEX ix_fact_venda_dt ON dw.fact_venda (id_empresa, data_key);
DROP TRIGGER IF EXISTS trg_dw_fact_venda_updated_at ON dw.fact_venda;
CREATE TRIGGER trg_dw_fact_venda_updated_at
BEFORE UPDATE ON dw.fact_venda
FOR EACH ROW EXECUTE FUNCTION auth.set_updated_at();

CREATE TABLE dw.fact_venda_item (
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  id_db             integer NOT NULL,
  id_movprodutos    integer NOT NULL,
  id_itensmovprodutos integer NOT NULL,
  data_key          integer NULL,
  id_produto        integer NOT NULL,
  id_grupo_produto  integer NULL,
  id_local_venda    integer NULL,
  id_funcionario    integer NULL,
  cfop              integer NULL,
  qtd               numeric(18,3) NULL,
  valor_unitario    numeric(18,4) NULL,
  total             numeric(18,2) NULL,
  desconto          numeric(18,2) NULL,
  custo_total       numeric(18,2) NULL,
  margem            numeric(18,2) NULL,
  payload           jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, id_filial, id_db, id_movprodutos, id_itensmovprodutos)
);
CREATE INDEX ix_fact_venda_item_dt ON dw.fact_venda_item (id_empresa, data_key);
CREATE INDEX ix_fact_venda_item_prod ON dw.fact_venda_item (id_empresa, id_produto);
DROP TRIGGER IF EXISTS trg_dw_fact_venda_item_updated_at ON dw.fact_venda_item;
CREATE TRIGGER trg_dw_fact_venda_item_updated_at
BEFORE UPDATE ON dw.fact_venda_item
FOR EACH ROW EXECUTE FUNCTION auth.set_updated_at();

-- Finance unified fact
CREATE TABLE dw.fact_financeiro (
  id_empresa        integer NOT NULL,
  id_filial         integer NOT NULL,
  id_db             integer NOT NULL,
  tipo_titulo       integer NOT NULL, -- 0 pagar, 1 receber
  id_titulo         integer NOT NULL,
  id_entidade       integer NULL,
  data_emissao      date NULL,
  data_key_emissao  integer NULL,
  vencimento        date NULL,
  data_key_venc     integer NULL,
  data_pagamento    date NULL,
  data_key_pgto     integer NULL,
  valor             numeric(18,2) NULL,
  valor_pago        numeric(18,2) NULL,
  payload           jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, id_filial, id_db, tipo_titulo, id_titulo)
);
CREATE INDEX ix_fact_fin_emissao ON dw.fact_financeiro (id_empresa, data_key_emissao);
CREATE INDEX ix_fact_fin_venc ON dw.fact_financeiro (id_empresa, data_key_venc);
DROP TRIGGER IF EXISTS trg_dw_fact_fin_updated_at ON dw.fact_financeiro;
CREATE TRIGGER trg_dw_fact_fin_updated_at
BEFORE UPDATE ON dw.fact_financeiro
FOR EACH ROW EXECUTE FUNCTION auth.set_updated_at();

-- =========================
-- ETL (watermark + helpers)
-- =========================

CREATE TABLE etl.watermark (
  id_empresa        integer NOT NULL,
  dataset           text NOT NULL,
  last_ingested_at  timestamptz NOT NULL DEFAULT '1970-01-01'::timestamptz,
  updated_at        timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_empresa, dataset)
);

CREATE TABLE etl.run_log (
  id                bigserial PRIMARY KEY,
  started_at        timestamptz NOT NULL DEFAULT now(),
  finished_at       timestamptz NULL,
  id_empresa        integer NOT NULL,
  meta              jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE OR REPLACE FUNCTION etl.date_key(p_ts timestamp)
RETURNS integer AS $$
  SELECT CASE WHEN p_ts IS NULL THEN NULL ELSE to_char(p_ts::date,'YYYYMMDD')::int END;
$$ LANGUAGE sql IMMUTABLE;

CREATE OR REPLACE FUNCTION etl.to_bool(p_text text)
RETURNS boolean AS $$
  SELECT CASE
    WHEN p_text IS NULL THEN false
    WHEN lower(p_text) IN ('1','true','t','yes','y') THEN true
    ELSE false
  END;
$$ LANGUAGE sql IMMUTABLE;

CREATE OR REPLACE FUNCTION etl.safe_int(p_text text)
RETURNS integer AS $$
DECLARE v integer;
BEGIN
  IF p_text IS NULL OR btrim(p_text) = '' THEN
    RETURN NULL;
  END IF;
  BEGIN
    v := p_text::integer;
    RETURN v;
  EXCEPTION WHEN others THEN
    BEGIN
      v := regexp_replace(p_text, '[^0-9-]', '', 'g')::integer;
      RETURN v;
    EXCEPTION WHEN others THEN
      RETURN NULL;
    END;
  END;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE OR REPLACE FUNCTION etl.safe_numeric(p_text text)
RETURNS numeric AS $$
DECLARE v numeric;
BEGIN
  IF p_text IS NULL OR btrim(p_text) = '' THEN
    RETURN NULL;
  END IF;
  BEGIN
    -- numeric supports exponent in most cases; if not, fallback to float
    v := p_text::numeric;
    RETURN v;
  EXCEPTION WHEN others THEN
    BEGIN
      v := (p_text::double precision)::numeric;
      RETURN v;
    EXCEPTION WHEN others THEN
      RETURN NULL;
    END;
  END;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE OR REPLACE FUNCTION etl.safe_timestamp(p_text text)
RETURNS timestamp AS $$
DECLARE v timestamp;
BEGIN
  IF p_text IS NULL OR btrim(p_text) = '' THEN
    RETURN NULL;
  END IF;
  BEGIN
    v := p_text::timestamp;
    RETURN v;
  EXCEPTION WHEN others THEN
    RETURN NULL;
  END;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE OR REPLACE FUNCTION etl.get_watermark(p_id_empresa int, p_dataset text)
RETURNS timestamptz AS $$
  SELECT last_ingested_at FROM etl.watermark WHERE id_empresa = p_id_empresa AND dataset = p_dataset;
$$ LANGUAGE sql STABLE;

CREATE OR REPLACE FUNCTION etl.set_watermark(p_id_empresa int, p_dataset text, p_ts timestamptz)
RETURNS void AS $$
BEGIN
  INSERT INTO etl.watermark (id_empresa, dataset, last_ingested_at)
  VALUES (p_id_empresa, p_dataset, COALESCE(p_ts, '1970-01-01'::timestamptz))
  ON CONFLICT (id_empresa, dataset)
  DO UPDATE SET last_ingested_at = EXCLUDED.last_ingested_at, updated_at = now();
END;
$$ LANGUAGE plpgsql;

-- =========================
-- ETL Loads (STG -> DW)
-- =========================

CREATE OR REPLACE FUNCTION etl.load_dim_filial(p_id_empresa int)
RETURNS integer AS $$
DECLARE v_rows integer;
BEGIN
  WITH src AS (
    SELECT
      id_empresa,
      id_filial,
      COALESCE(payload->>'NOMEFILIAL', payload->>'NOME', payload->>'RAZAOSOCIALFILIAL', '') AS nome,
      COALESCE(payload->>'CNPJ', payload->>'cnpj', payload->>'CNPJCPF', NULL) AS cnpj,
      COALESCE(payload->>'RAZAOSOCIALFILIAL', NULL) AS razao_social
    FROM stg.filiais
    WHERE id_empresa = p_id_empresa
  )
  INSERT INTO dw.dim_filial (id_empresa,id_filial,nome,cnpj,razao_social)
  SELECT id_empresa,id_filial,nome,cnpj,razao_social FROM src
  ON CONFLICT (id_empresa,id_filial)
  DO UPDATE SET nome=EXCLUDED.nome, cnpj=EXCLUDED.cnpj, razao_social=EXCLUDED.razao_social;

  GET DIAGNOSTICS v_rows = ROW_COUNT;

  -- keep auth.filiais in sync (for UI/access)
  INSERT INTO auth.filiais (id_empresa,id_filial,nome)
  SELECT id_empresa,id_filial,nome FROM dw.dim_filial WHERE id_empresa = p_id_empresa
  ON CONFLICT (id_empresa,id_filial) DO UPDATE SET nome=EXCLUDED.nome, is_active=true;

  RETURN v_rows;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION etl.load_dim_grupos(p_id_empresa int)
RETURNS integer AS $$
DECLARE v_rows integer;
BEGIN
  WITH src AS (
    SELECT
      id_empresa,
      id_filial,
      id_grupoprodutos AS id_grupo_produto,
      COALESCE(payload->>'NOMEGRUPOPRODUTOS','') AS nome
    FROM stg.grupoprodutos
    WHERE id_empresa = p_id_empresa
  )
  INSERT INTO dw.dim_grupo_produto (id_empresa,id_filial,id_grupo_produto,nome)
  SELECT id_empresa,id_filial,id_grupo_produto,nome FROM src
  ON CONFLICT (id_empresa,id_filial,id_grupo_produto)
  DO UPDATE SET nome=EXCLUDED.nome;
  GET DIAGNOSTICS v_rows = ROW_COUNT;
  RETURN v_rows;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION etl.load_dim_localvendas(p_id_empresa int)
RETURNS integer AS $$
DECLARE v_rows integer;
BEGIN
  WITH src AS (
    SELECT
      id_empresa,
      id_filial,
      id_localvendas AS id_local_venda,
      COALESCE(payload->>'NOMELOCALVENDAS','') AS nome
    FROM stg.localvendas
    WHERE id_empresa = p_id_empresa
  )
  INSERT INTO dw.dim_local_venda (id_empresa,id_filial,id_local_venda,nome)
  SELECT id_empresa,id_filial,id_local_venda,nome FROM src
  ON CONFLICT (id_empresa,id_filial,id_local_venda)
  DO UPDATE SET nome=EXCLUDED.nome;
  GET DIAGNOSTICS v_rows = ROW_COUNT;
  RETURN v_rows;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION etl.load_dim_produtos(p_id_empresa int)
RETURNS integer AS $$
DECLARE v_rows integer;
BEGIN
  WITH src AS (
    SELECT
      p.id_empresa,
      p.id_filial,
      p.id_produto,
      COALESCE(p.payload->>'NOMEPRODUTO', p.payload->>'NOME', '') AS nome,
      NULLIF(p.payload->>'UNIDADE','') AS unidade,
      etl.safe_int(p.payload->>'ID_GRUPOPRODUTOS') AS id_grupo_produto,
      etl.safe_int(p.payload->>'ID_LOCALVENDAS') AS id_local_venda,
      etl.safe_numeric(p.payload->>'customedio') AS custo_medio
    FROM stg.produtos p
    WHERE p.id_empresa = p_id_empresa
  )
  INSERT INTO dw.dim_produto (id_empresa,id_filial,id_produto,nome,unidade,id_grupo_produto,id_local_venda,custo_medio)
  SELECT id_empresa,id_filial,id_produto,nome,unidade,id_grupo_produto,id_local_venda,custo_medio FROM src
  ON CONFLICT (id_empresa,id_filial,id_produto)
  DO UPDATE SET
    nome=EXCLUDED.nome,
    unidade=EXCLUDED.unidade,
    id_grupo_produto=EXCLUDED.id_grupo_produto,
    id_local_venda=EXCLUDED.id_local_venda,
    custo_medio=EXCLUDED.custo_medio;

  GET DIAGNOSTICS v_rows = ROW_COUNT;
  RETURN v_rows;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION etl.load_dim_funcionarios(p_id_empresa int)
RETURNS integer AS $$
DECLARE v_rows integer;
BEGIN
  WITH src AS (
    SELECT
      id_empresa,
      id_filial,
      id_funcionario,
      COALESCE(payload->>'NOMEFUNCIONARIO', payload->>'NOME', '') AS nome
    FROM stg.funcionarios
    WHERE id_empresa = p_id_empresa
  )
  INSERT INTO dw.dim_funcionario (id_empresa,id_filial,id_funcionario,nome)
  SELECT id_empresa,id_filial,id_funcionario,nome FROM src
  ON CONFLICT (id_empresa,id_filial,id_funcionario)
  DO UPDATE SET nome=EXCLUDED.nome;
  GET DIAGNOSTICS v_rows = ROW_COUNT;
  RETURN v_rows;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION etl.load_dim_clientes(p_id_empresa int)
RETURNS integer AS $$
DECLARE v_rows integer;
BEGIN
  WITH src AS (
    SELECT
      id_empresa,
      id_filial,
      id_entidade AS id_cliente,
      COALESCE(payload->>'NOMEENTIDADE', payload->>'NOME', '') AS nome,
      COALESCE(payload->>'CNPJCPF', payload->>'DOCUMENTO', NULL) AS documento
    FROM stg.entidades
    WHERE id_empresa = p_id_empresa
  )
  INSERT INTO dw.dim_cliente (id_empresa,id_filial,id_cliente,nome,documento)
  SELECT id_empresa,id_filial,id_cliente,nome,documento FROM src
  ON CONFLICT (id_empresa,id_filial,id_cliente)
  DO UPDATE SET nome=EXCLUDED.nome, documento=EXCLUDED.documento;

  GET DIAGNOSTICS v_rows = ROW_COUNT;
  RETURN v_rows;
END;
$$ LANGUAGE plpgsql;

-- Facts incremental loads using watermark (ingested_at)

CREATE OR REPLACE FUNCTION etl.load_fact_comprovante(p_id_empresa int)
RETURNS integer AS $$
DECLARE
  v_wm timestamptz;
  v_max timestamptz;
  v_rows integer;
BEGIN
  v_wm := COALESCE(etl.get_watermark(p_id_empresa, 'comprovantes'), '1970-01-01'::timestamptz);

  WITH src AS (
    SELECT
      id_empresa,
      id_filial,
      id_db,
      id_comprovante,
      etl.safe_timestamp(payload->>'DATA') AS data,
      etl.date_key(etl.safe_timestamp(payload->>'DATA')) AS data_key,
      etl.safe_int(payload->>'ID_USUARIOS') AS id_usuario,
      etl.safe_int(payload->>'ID_TURNOS') AS id_turno,
      etl.safe_int(payload->>'ID_ENTIDADE') AS id_cliente,
      etl.safe_numeric(payload->>'VLRTOTAL')::numeric(18,2) AS valor_total,
      etl.to_bool(payload->>'CANCELADO') AS cancelado,
      etl.safe_int(payload->>'SITUACAO') AS situacao,
      payload,
      ingested_at
    FROM stg.comprovantes
    WHERE id_empresa = p_id_empresa
      AND ingested_at > v_wm
  )
  INSERT INTO dw.fact_comprovante (
    id_empresa,id_filial,id_db,id_comprovante,data,data_key,id_usuario,id_turno,id_cliente,valor_total,cancelado,situacao,payload
  )
  SELECT
    id_empresa,id_filial,id_db,id_comprovante,data,data_key,id_usuario,id_turno,id_cliente,valor_total,cancelado,situacao,payload
  FROM src
  ON CONFLICT (id_empresa,id_filial,id_db,id_comprovante)
  DO UPDATE SET
    data=EXCLUDED.data,
    data_key=EXCLUDED.data_key,
    id_usuario=EXCLUDED.id_usuario,
    id_turno=EXCLUDED.id_turno,
    id_cliente=EXCLUDED.id_cliente,
    valor_total=EXCLUDED.valor_total,
    cancelado=EXCLUDED.cancelado,
    situacao=EXCLUDED.situacao,
    payload=EXCLUDED.payload;

  GET DIAGNOSTICS v_rows = ROW_COUNT;

  SELECT MAX(ingested_at) INTO v_max FROM stg.comprovantes WHERE id_empresa = p_id_empresa;
  PERFORM etl.set_watermark(p_id_empresa, 'comprovantes', COALESCE(v_max, v_wm));

  RETURN v_rows;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION etl.load_fact_venda(p_id_empresa int)
RETURNS integer AS $$
DECLARE
  v_wm timestamptz;
  v_max timestamptz;
  v_rows integer;
BEGIN
  v_wm := COALESCE(etl.get_watermark(p_id_empresa, 'movprodutos'), '1970-01-01'::timestamptz);

  WITH src AS (
    SELECT
      m.id_empresa,
      m.id_filial,
      m.id_db,
      m.id_movprodutos,
      etl.safe_timestamp(m.payload->>'DATA') AS data,
      etl.date_key(etl.safe_timestamp(m.payload->>'DATA')) AS data_key,
      etl.safe_int(m.payload->>'ID_USUARIOS') AS id_usuario,
      etl.safe_int(m.payload->>'ID_ENTIDADE') AS id_cliente,
      etl.safe_int(m.payload->>'ID_COMPROVANTE') AS id_comprovante,
      etl.safe_int(m.payload->>'ID_TURNOS') AS id_turno,
      etl.safe_int(m.payload->>'SAIDAS_ENTRADAS') AS saidas_entradas,
      etl.safe_numeric(m.payload->>'TOTALVENDA')::numeric(18,2) AS total_venda,
      m.payload,
      m.ingested_at
    FROM stg.movprodutos m
    WHERE m.id_empresa = p_id_empresa
      AND m.ingested_at > v_wm
  ), upserted AS (
    INSERT INTO dw.fact_venda (
      id_empresa,id_filial,id_db,id_movprodutos,data,data_key,id_usuario,id_cliente,id_comprovante,id_turno,saidas_entradas,total_venda,payload
    )
    SELECT
      id_empresa,id_filial,id_db,id_movprodutos,data,data_key,id_usuario,id_cliente,id_comprovante,id_turno,saidas_entradas,total_venda,payload
    FROM src
    ON CONFLICT (id_empresa,id_filial,id_db,id_movprodutos)
    DO UPDATE SET
      data=EXCLUDED.data,
      data_key=EXCLUDED.data_key,
      id_usuario=EXCLUDED.id_usuario,
      id_cliente=EXCLUDED.id_cliente,
      id_comprovante=EXCLUDED.id_comprovante,
      id_turno=EXCLUDED.id_turno,
      saidas_entradas=EXCLUDED.saidas_entradas,
      total_venda=EXCLUDED.total_venda,
      payload=EXCLUDED.payload
    RETURNING 1
  )
  SELECT COUNT(*) INTO v_rows FROM upserted;

  -- Update cancelado flag from comprovantes (if present)
  UPDATE dw.fact_venda v
  SET cancelado = c.cancelado
  FROM dw.fact_comprovante c
  WHERE v.id_empresa = p_id_empresa
    AND v.id_empresa = c.id_empresa
    AND v.id_filial = c.id_filial
    AND v.id_db = c.id_db
    AND v.id_comprovante IS NOT NULL
    AND v.id_comprovante = c.id_comprovante;

  SELECT MAX(ingested_at) INTO v_max FROM stg.movprodutos WHERE id_empresa = p_id_empresa;
  PERFORM etl.set_watermark(p_id_empresa, 'movprodutos', COALESCE(v_max, v_wm));

  RETURN v_rows;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION etl.load_fact_venda_item(p_id_empresa int)
RETURNS integer AS $$
DECLARE
  v_wm timestamptz;
  v_max timestamptz;
  v_rows integer;
BEGIN
  v_wm := COALESCE(etl.get_watermark(p_id_empresa, 'itensmovprodutos'), '1970-01-01'::timestamptz);

  WITH src AS (
    SELECT
      i.id_empresa,
      i.id_filial,
      i.id_db,
      i.id_movprodutos,
      i.id_itensmovprodutos,
      v.data_key,
      etl.safe_int(i.payload->>'ID_PRODUTOS') AS id_produto,
      etl.safe_int(i.payload->>'ID_GRUPOPRODUTOS') AS id_grupo_produto,
      etl.safe_int(i.payload->>'ID_LOCALVENDAS') AS id_local_venda,
      etl.safe_int(i.payload->>'ID_FUNCIONARIOS') AS id_funcionario,
      etl.safe_int(i.payload->>'CFOP') AS cfop,
      etl.safe_numeric(i.payload->>'QTDE')::numeric(18,3) AS qtd,
      etl.safe_numeric(i.payload->>'VLRUNITARIO')::numeric(18,4) AS valor_unitario,
      etl.safe_numeric(i.payload->>'TOTAL')::numeric(18,2) AS total,
      etl.safe_numeric(i.payload->>'VLRDESCONTO')::numeric(18,2) AS desconto,
      -- custo_total: prefer VLRCUSTO, fallback dim_produto.custo_medio
      COALESCE(
        (etl.safe_numeric(i.payload->>'VLRCUSTO')::numeric(18,6) * etl.safe_numeric(i.payload->>'QTDE')::numeric(18,6))::numeric(18,2),
        (dp.custo_medio * etl.safe_numeric(i.payload->>'QTDE')::numeric(18,6))::numeric(18,2)
      ) AS custo_total,
      i.payload,
      i.ingested_at
    FROM stg.itensmovprodutos i
    LEFT JOIN dw.fact_venda v
      ON v.id_empresa=i.id_empresa AND v.id_filial=i.id_filial AND v.id_db=i.id_db AND v.id_movprodutos=i.id_movprodutos
    LEFT JOIN dw.dim_produto dp
      ON dp.id_empresa=i.id_empresa AND dp.id_filial=i.id_filial AND dp.id_produto=etl.safe_int(i.payload->>'ID_PRODUTOS')
    WHERE i.id_empresa = p_id_empresa
      AND i.ingested_at > v_wm
  ), upserted AS (
    INSERT INTO dw.fact_venda_item (
      id_empresa,id_filial,id_db,id_movprodutos,id_itensmovprodutos,data_key,
      id_produto,id_grupo_produto,id_local_venda,id_funcionario,cfop,
      qtd,valor_unitario,total,desconto,custo_total,margem,payload
    )
    SELECT
      id_empresa,id_filial,id_db,id_movprodutos,id_itensmovprodutos,data_key,
      id_produto,id_grupo_produto,id_local_venda,id_funcionario,cfop,
      qtd,valor_unitario,total,desconto,custo_total,
      (COALESCE(total,0) - COALESCE(custo_total,0))::numeric(18,2) AS margem,
      payload
    FROM src
    ON CONFLICT (id_empresa,id_filial,id_db,id_movprodutos,id_itensmovprodutos)
    DO UPDATE SET
      data_key=EXCLUDED.data_key,
      id_produto=EXCLUDED.id_produto,
      id_grupo_produto=EXCLUDED.id_grupo_produto,
      id_local_venda=EXCLUDED.id_local_venda,
      id_funcionario=EXCLUDED.id_funcionario,
      cfop=EXCLUDED.cfop,
      qtd=EXCLUDED.qtd,
      valor_unitario=EXCLUDED.valor_unitario,
      total=EXCLUDED.total,
      desconto=EXCLUDED.desconto,
      custo_total=EXCLUDED.custo_total,
      margem=EXCLUDED.margem,
      payload=EXCLUDED.payload
    RETURNING 1
  )
  SELECT COUNT(*) INTO v_rows FROM upserted;

  SELECT MAX(ingested_at) INTO v_max FROM stg.itensmovprodutos WHERE id_empresa = p_id_empresa;
  PERFORM etl.set_watermark(p_id_empresa, 'itensmovprodutos', COALESCE(v_max, v_wm));

  RETURN v_rows;
END;
$$ LANGUAGE plpgsql;

-- Finance: supports either stg.financeiro OR stg.contaspagar/contasreceber
CREATE OR REPLACE FUNCTION etl.load_fact_financeiro(p_id_empresa int)
RETURNS integer AS $$
DECLARE v_rows integer := 0;
DECLARE v_rows_a integer := 0;
DECLARE v_rows_b integer := 0;
BEGIN
  -- A) Unified dataset
  WITH src AS (
    SELECT
      f.id_empresa,
      f.id_filial,
      f.id_db,
      f.tipo_titulo,
      f.id_titulo,
      etl.safe_int(f.payload->>'ID_ENTIDADE') AS id_entidade,
      (etl.safe_timestamp(f.payload->>'DTACONTA'))::date AS data_emissao,
      etl.date_key(etl.safe_timestamp(f.payload->>'DTACONTA')) AS data_key_emissao,
      (etl.safe_timestamp(f.payload->>'DTAVCTO'))::date AS vencimento,
      etl.date_key(etl.safe_timestamp(f.payload->>'DTAVCTO')) AS data_key_venc,
      (etl.safe_timestamp(f.payload->>'DTAPGTO'))::date AS data_pagamento,
      etl.date_key(etl.safe_timestamp(f.payload->>'DTAPGTO')) AS data_key_pgto,
      etl.safe_numeric(f.payload->>'VALOR')::numeric(18,2) AS valor,
      etl.safe_numeric(f.payload->>'VLRPAGO')::numeric(18,2) AS valor_pago,
      f.payload
    FROM stg.financeiro f
    WHERE f.id_empresa = p_id_empresa
  )
  INSERT INTO dw.fact_financeiro (
    id_empresa,id_filial,id_db,tipo_titulo,id_titulo,id_entidade,
    data_emissao,data_key_emissao,vencimento,data_key_venc,data_pagamento,data_key_pgto,
    valor,valor_pago,payload
  )
  SELECT
    id_empresa,id_filial,id_db,tipo_titulo,id_titulo,id_entidade,
    data_emissao,data_key_emissao,vencimento,data_key_venc,data_pagamento,data_key_pgto,
    valor,valor_pago,payload
  FROM src
  ON CONFLICT (id_empresa,id_filial,id_db,tipo_titulo,id_titulo)
  DO UPDATE SET
    id_entidade=EXCLUDED.id_entidade,
    data_emissao=EXCLUDED.data_emissao,
    data_key_emissao=EXCLUDED.data_key_emissao,
    vencimento=EXCLUDED.vencimento,
    data_key_venc=EXCLUDED.data_key_venc,
    data_pagamento=EXCLUDED.data_pagamento,
    data_key_pgto=EXCLUDED.data_key_pgto,
    valor=EXCLUDED.valor,
    valor_pago=EXCLUDED.valor_pago,
    payload=EXCLUDED.payload;

  GET DIAGNOSTICS v_rows_a = ROW_COUNT;

  -- B) Raw contaspagar/contasreceber (if unified not used)
  WITH src AS (
    SELECT
      p.id_empresa,
      p.id_filial,
      p.id_db,
      0 AS tipo_titulo,
      p.id_contaspagar AS id_titulo,
      etl.safe_int(p.payload->>'ID_ENTIDADE') AS id_entidade,
      (etl.safe_timestamp(p.payload->>'DTACONTA'))::date AS data_emissao,
      etl.date_key(etl.safe_timestamp(p.payload->>'DTACONTA')) AS data_key_emissao,
      (etl.safe_timestamp(p.payload->>'DTAVCTO'))::date AS vencimento,
      etl.date_key(etl.safe_timestamp(p.payload->>'DTAVCTO')) AS data_key_venc,
      (etl.safe_timestamp(p.payload->>'DTAPGTO'))::date AS data_pagamento,
      etl.date_key(etl.safe_timestamp(p.payload->>'DTAPGTO')) AS data_key_pgto,
      etl.safe_numeric(p.payload->>'VALOR')::numeric(18,2) AS valor,
      etl.safe_numeric(p.payload->>'VLRPAGO')::numeric(18,2) AS valor_pago,
      p.payload
    FROM stg.contaspagar p
    WHERE p.id_empresa = p_id_empresa

    UNION ALL

    SELECT
      r.id_empresa,
      r.id_filial,
      r.id_db,
      1 AS tipo_titulo,
      r.id_contasreceber AS id_titulo,
      etl.safe_int(r.payload->>'ID_ENTIDADE') AS id_entidade,
      (etl.safe_timestamp(r.payload->>'DTACONTA'))::date AS data_emissao,
      etl.date_key(etl.safe_timestamp(r.payload->>'DTACONTA')) AS data_key_emissao,
      (etl.safe_timestamp(r.payload->>'DTAVCTO'))::date AS vencimento,
      etl.date_key(etl.safe_timestamp(r.payload->>'DTAVCTO')) AS data_key_venc,
      (etl.safe_timestamp(r.payload->>'DTAPGTO'))::date AS data_pagamento,
      etl.date_key(etl.safe_timestamp(r.payload->>'DTAPGTO')) AS data_key_pgto,
      etl.safe_numeric(r.payload->>'VALOR')::numeric(18,2) AS valor,
      etl.safe_numeric(r.payload->>'VLRPAGO')::numeric(18,2) AS valor_pago,
      r.payload
    FROM stg.contasreceber r
    WHERE r.id_empresa = p_id_empresa
  )
  INSERT INTO dw.fact_financeiro (
    id_empresa,id_filial,id_db,tipo_titulo,id_titulo,id_entidade,
    data_emissao,data_key_emissao,vencimento,data_key_venc,data_pagamento,data_key_pgto,
    valor,valor_pago,payload
  )
  SELECT
    id_empresa,id_filial,id_db,tipo_titulo,id_titulo,id_entidade,
    data_emissao,data_key_emissao,vencimento,data_key_venc,data_pagamento,data_key_pgto,
    valor,valor_pago,payload
  FROM src
  ON CONFLICT (id_empresa,id_filial,id_db,tipo_titulo,id_titulo)
  DO UPDATE SET
    id_entidade=EXCLUDED.id_entidade,
    data_emissao=EXCLUDED.data_emissao,
    data_key_emissao=EXCLUDED.data_key_emissao,
    vencimento=EXCLUDED.vencimento,
    data_key_venc=EXCLUDED.data_key_venc,
    data_pagamento=EXCLUDED.data_pagamento,
    data_key_pgto=EXCLUDED.data_key_pgto,
    valor=EXCLUDED.valor,
    valor_pago=EXCLUDED.valor_pago,
    payload=EXCLUDED.payload;

  GET DIAGNOSTICS v_rows_b = ROW_COUNT;

  v_rows := v_rows_a + v_rows_b;
  RETURN v_rows;
END;
$$ LANGUAGE plpgsql;

-- =========================
-- MART (materialized views)
-- =========================

-- IMPORTANT: for speed, dashboards read MART; ETL ends with refresh_mart().

CREATE MATERIALIZED VIEW mart.agg_vendas_diaria AS
SELECT
  v.id_empresa,
  v.id_filial,
  v.data_key,
  COALESCE(SUM(i.total),0)::numeric(18,2) AS faturamento,
  COALESCE(COUNT(*),0)::int AS quantidade_itens,
  COALESCE(SUM(i.margem),0)::numeric(18,2) AS margem,
  CASE WHEN COUNT(DISTINCT v.id_comprovante) = 0 THEN 0
       ELSE (SUM(i.total) / COUNT(DISTINCT v.id_comprovante))::numeric(18,2)
  END AS ticket_medio,
  now() AS updated_at
FROM dw.fact_venda v
JOIN dw.fact_venda_item i
  ON i.id_empresa=v.id_empresa AND i.id_filial=v.id_filial AND i.id_db=v.id_db AND i.id_movprodutos=v.id_movprodutos
WHERE v.data_key IS NOT NULL
  AND COALESCE(v.cancelado,false) = false
  AND COALESCE(i.cfop,0) >= 5000
GROUP BY 1,2,3;

CREATE UNIQUE INDEX ux_mart_agg_vendas_diaria ON mart.agg_vendas_diaria (id_empresa,id_filial,data_key);
CREATE INDEX ix_mart_agg_vendas_diaria_empresa_data ON mart.agg_vendas_diaria (id_empresa, data_key);

CREATE MATERIALIZED VIEW mart.insights_base_diaria AS
WITH daily AS (
  SELECT
    a.id_empresa,
    a.id_filial,
    a.data_key,
    to_date(a.data_key::text,'YYYYMMDD') AS dt,
    a.faturamento AS faturamento_dia
  FROM mart.agg_vendas_diaria a
), daily_cum AS (
  SELECT
    d.*,
    SUM(d.faturamento_dia) OVER (
      PARTITION BY d.id_empresa, d.id_filial, date_trunc('month', d.dt)
      ORDER BY d.dt
      ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    )::numeric(18,2) AS faturamento_mes_acum
  FROM daily d
), prev_join AS (
  SELECT
    cur.id_empresa,
    cur.id_filial,
    cur.data_key,
    cur.faturamento_dia,
    cur.faturamento_mes_acum,
    COALESCE(prev.faturamento_mes_acum, 0)::numeric(18,2) AS faturamento_mes_anterior_acum
  FROM daily_cum cur
  LEFT JOIN daily_cum prev
    ON prev.id_empresa = cur.id_empresa
   AND prev.id_filial = cur.id_filial
   AND prev.dt = (cur.dt - interval '1 month')::date
)
SELECT
  id_empresa,
  id_filial,
  data_key,
  faturamento_dia,
  faturamento_mes_acum,
  (faturamento_mes_acum - faturamento_mes_anterior_acum)::numeric(18,2) AS comparativo_mes_anterior,
  NULL::text AS top_vendedor_key,
  NULL::numeric(18,2) AS top_vendedor_valor,
  NULL::numeric(18,2) AS inadimplencia_valor,
  NULL::numeric(9,4)  AS inadimplencia_pct,
  NULL::text AS cliente_em_risco_key,
  NULL::numeric(9,4) AS margem_media_pct,
  NULL::numeric(18,2) AS giro_estoque,
  now() AS updated_at,
  '{}'::jsonb AS batch_info
FROM prev_join;

CREATE UNIQUE INDEX ux_mart_insights_base_diaria ON mart.insights_base_diaria (id_empresa,id_filial,data_key);
CREATE INDEX ix_mart_insights_base_diaria_empresa_data ON mart.insights_base_diaria (id_empresa, data_key);

-- Sales by hour
CREATE MATERIALIZED VIEW mart.agg_vendas_hora AS
SELECT
  v.id_empresa,
  v.id_filial,
  v.data_key,
  EXTRACT(HOUR FROM v.data)::int AS hora,
  COALESCE(SUM(i.total),0)::numeric(18,2) AS faturamento,
  COALESCE(SUM(i.margem),0)::numeric(18,2) AS margem,
  COALESCE(COUNT(DISTINCT v.id_comprovante),0)::int AS vendas,
  now() AS updated_at
FROM dw.fact_venda v
JOIN dw.fact_venda_item i
  ON i.id_empresa=v.id_empresa AND i.id_filial=v.id_filial AND i.id_db=v.id_db AND i.id_movprodutos=v.id_movprodutos
WHERE v.data IS NOT NULL AND v.data_key IS NOT NULL
  AND COALESCE(v.cancelado,false) = false
  AND COALESCE(i.cfop,0) >= 5000
GROUP BY 1,2,3,4;

CREATE UNIQUE INDEX ux_mart_agg_vendas_hora ON mart.agg_vendas_hora (id_empresa,id_filial,data_key,hora);

-- Top products (daily)
CREATE MATERIALIZED VIEW mart.agg_produtos_diaria AS
SELECT
  v.id_empresa,
  v.id_filial,
  v.data_key,
  i.id_produto,
  COALESCE(p.nome,'') AS produto_nome,
  COALESCE(SUM(i.total),0)::numeric(18,2) AS faturamento,
  COALESCE(SUM(i.margem),0)::numeric(18,2) AS margem,
  COALESCE(SUM(i.qtd),0)::numeric(18,3) AS qtd,
  now() AS updated_at
FROM dw.fact_venda v
JOIN dw.fact_venda_item i
  ON i.id_empresa=v.id_empresa AND i.id_filial=v.id_filial AND i.id_db=v.id_db AND i.id_movprodutos=v.id_movprodutos
LEFT JOIN dw.dim_produto p
  ON p.id_empresa=i.id_empresa AND p.id_filial=i.id_filial AND p.id_produto=i.id_produto
WHERE v.data_key IS NOT NULL
  AND COALESCE(v.cancelado,false) = false
  AND COALESCE(i.cfop,0) >= 5000
GROUP BY 1,2,3,4,5;

CREATE INDEX ix_mart_agg_produtos_diaria_lookup ON mart.agg_produtos_diaria (id_empresa, data_key, faturamento DESC);

-- Top groups (daily)
CREATE MATERIALIZED VIEW mart.agg_grupos_diaria AS
SELECT
  v.id_empresa,
  v.id_filial,
  v.data_key,
  COALESCE(i.id_grupo_produto, -1) AS id_grupo_produto,
  COALESCE(g.nome,'(Sem grupo)') AS grupo_nome,
  COALESCE(SUM(i.total),0)::numeric(18,2) AS faturamento,
  COALESCE(SUM(i.margem),0)::numeric(18,2) AS margem,
  now() AS updated_at
FROM dw.fact_venda v
JOIN dw.fact_venda_item i
  ON i.id_empresa=v.id_empresa AND i.id_filial=v.id_filial AND i.id_db=v.id_db AND i.id_movprodutos=v.id_movprodutos
LEFT JOIN dw.dim_grupo_produto g
  ON g.id_empresa=i.id_empresa AND g.id_filial=i.id_filial AND g.id_grupo_produto=i.id_grupo_produto
WHERE v.data_key IS NOT NULL
  AND COALESCE(v.cancelado,false) = false
  AND COALESCE(i.cfop,0) >= 5000
GROUP BY 1,2,3,4,5;

CREATE INDEX ix_mart_agg_grupos_diaria_lookup ON mart.agg_grupos_diaria (id_empresa, data_key, faturamento DESC);

-- Team (employees) daily
CREATE MATERIALIZED VIEW mart.agg_funcionarios_diaria AS
SELECT
  v.id_empresa,
  v.id_filial,
  v.data_key,
  COALESCE(i.id_funcionario, -1) AS id_funcionario,
  COALESCE(f.nome,'(Sem funcionário)') AS funcionario_nome,
  COALESCE(SUM(i.total),0)::numeric(18,2) AS faturamento,
  COALESCE(SUM(i.margem),0)::numeric(18,2) AS margem,
  COALESCE(COUNT(DISTINCT v.id_comprovante),0)::int AS vendas,
  now() AS updated_at
FROM dw.fact_venda v
JOIN dw.fact_venda_item i
  ON i.id_empresa=v.id_empresa AND i.id_filial=v.id_filial AND i.id_db=v.id_db AND i.id_movprodutos=v.id_movprodutos
LEFT JOIN dw.dim_funcionario f
  ON f.id_empresa=i.id_empresa AND f.id_filial=i.id_filial AND f.id_funcionario=i.id_funcionario
WHERE v.data_key IS NOT NULL
  AND COALESCE(v.cancelado,false) = false
  AND COALESCE(i.cfop,0) >= 5000
GROUP BY 1,2,3,4,5;

CREATE INDEX ix_mart_agg_funcionarios_diaria_lookup ON mart.agg_funcionarios_diaria (id_empresa, data_key, faturamento DESC);

-- Fraud: cancelamentos (daily)
CREATE MATERIALIZED VIEW mart.fraude_cancelamentos_diaria AS
SELECT
  c.id_empresa,
  c.id_filial,
  c.data_key,
  COUNT(*)::int AS cancelamentos,
  COALESCE(SUM(c.valor_total),0)::numeric(18,2) AS valor_cancelado,
  now() AS updated_at
FROM dw.fact_comprovante c
WHERE c.data_key IS NOT NULL
  AND c.cancelado = true
GROUP BY 1,2,3;

CREATE UNIQUE INDEX ux_mart_fraude_cancelamentos_diaria ON mart.fraude_cancelamentos_diaria (id_empresa,id_filial,data_key);

-- Fraud: last cancel events (lightweight view)
CREATE MATERIALIZED VIEW mart.fraude_cancelamentos_eventos AS
SELECT
  c.id_empresa,
  c.id_filial,
  c.id_db,
  c.id_comprovante,
  c.data,
  c.data_key,
  c.id_usuario,
  c.id_turno,
  c.valor_total,
  now() AS updated_at
FROM dw.fact_comprovante c
WHERE c.cancelado = true;

CREATE INDEX ix_mart_fraude_eventos_dt ON mart.fraude_cancelamentos_eventos (id_empresa, data DESC);

-- Finance: vencimentos (daily)
CREATE MATERIALIZED VIEW mart.financeiro_vencimentos_diaria AS
SELECT
  f.id_empresa,
  f.id_filial,
  f.data_key_venc AS data_key,
  f.tipo_titulo,
  COALESCE(SUM(f.valor),0)::numeric(18,2) AS valor_total,
  COALESCE(SUM(f.valor_pago),0)::numeric(18,2) AS valor_pago,
  COALESCE(SUM(CASE WHEN f.data_pagamento IS NULL THEN COALESCE(f.valor,0) - COALESCE(f.valor_pago,0) ELSE 0 END),0)::numeric(18,2) AS valor_aberto,
  now() AS updated_at
FROM dw.fact_financeiro f
WHERE f.data_key_venc IS NOT NULL
GROUP BY 1,2,3,4;

CREATE INDEX ix_mart_fin_venc_lookup ON mart.financeiro_vencimentos_diaria (id_empresa, data_key, tipo_titulo);

-- =========================
-- ETL: refresh marts
-- =========================

CREATE OR REPLACE FUNCTION etl.refresh_marts()
RETURNS void AS $$
BEGIN
  -- NOTE: These refreshes rebuild the whole MV. For large tenants, we can evolve to incremental MART tables.
  REFRESH MATERIALIZED VIEW mart.agg_vendas_diaria;
  REFRESH MATERIALIZED VIEW mart.insights_base_diaria;
  REFRESH MATERIALIZED VIEW mart.agg_vendas_hora;
  REFRESH MATERIALIZED VIEW mart.agg_produtos_diaria;
  REFRESH MATERIALIZED VIEW mart.agg_grupos_diaria;
  REFRESH MATERIALIZED VIEW mart.agg_funcionarios_diaria;
  REFRESH MATERIALIZED VIEW mart.fraude_cancelamentos_diaria;
  REFRESH MATERIALIZED VIEW mart.fraude_cancelamentos_eventos;
  REFRESH MATERIALIZED VIEW mart.financeiro_vencimentos_diaria;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION etl.run_all(p_id_empresa int, p_refresh_mart boolean DEFAULT true)
RETURNS jsonb AS $$
DECLARE
  v_started timestamptz := now();
  v_meta jsonb := '{}'::jsonb;
  v_id bigint;
BEGIN
  INSERT INTO etl.run_log (id_empresa, meta) VALUES (p_id_empresa, jsonb_build_object('status','running'))
  RETURNING id INTO v_id;

  v_meta := v_meta || jsonb_build_object('dim_filial', etl.load_dim_filial(p_id_empresa));
  v_meta := v_meta || jsonb_build_object('dim_grupos', etl.load_dim_grupos(p_id_empresa));
  v_meta := v_meta || jsonb_build_object('dim_localvendas', etl.load_dim_localvendas(p_id_empresa));
  v_meta := v_meta || jsonb_build_object('dim_produtos', etl.load_dim_produtos(p_id_empresa));
  v_meta := v_meta || jsonb_build_object('dim_funcionarios', etl.load_dim_funcionarios(p_id_empresa));
  v_meta := v_meta || jsonb_build_object('dim_clientes', etl.load_dim_clientes(p_id_empresa));

  v_meta := v_meta || jsonb_build_object('fact_comprovante', etl.load_fact_comprovante(p_id_empresa));
  v_meta := v_meta || jsonb_build_object('fact_venda', etl.load_fact_venda(p_id_empresa));
  v_meta := v_meta || jsonb_build_object('fact_venda_item', etl.load_fact_venda_item(p_id_empresa));
  v_meta := v_meta || jsonb_build_object('fact_financeiro', etl.load_fact_financeiro(p_id_empresa));

  IF p_refresh_mart THEN
    PERFORM etl.refresh_marts();
    v_meta := v_meta || jsonb_build_object('mart_refreshed', true);
  ELSE
    v_meta := v_meta || jsonb_build_object('mart_refreshed', false);
  END IF;

  UPDATE etl.run_log
  SET finished_at = now(), meta = v_meta
  WHERE id = v_id;

  RETURN jsonb_build_object(
    'ok', true,
    'id_empresa', p_id_empresa,
    'started_at', v_started,
    'finished_at', now(),
    'meta', v_meta
  );
END;
$$ LANGUAGE plpgsql;

-- Seed a default tenant (empresa 1) for dev
INSERT INTO app.tenants (id_empresa, nome) VALUES (1, 'Empresa 1 (dev)')
ON CONFLICT (id_empresa) DO NOTHING;

-- Keep at least one filial placeholder for MANAGER seed
INSERT INTO auth.filiais (id_empresa,id_filial,nome) VALUES (1,1,'Filial 1')
ON CONFLICT DO NOTHING;
INSERT INTO dw.dim_filial (id_empresa,id_filial,nome) VALUES (1,1,'Filial 1')
ON CONFLICT DO NOTHING;

COMMIT;
